name: Build Server CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: Install npm packages
      run: npm install -w apps/server
    - name: Build the Server-side code
      run: npm run -w apps/server build
